// <auto-generated />
namespace Gestion_garage_access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addbontoemployer31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addbontoemployer31));
        
        string IMigrationMetadata.Id
        {
            get { return "201902091647441_Addbontoemployer31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
